### ISSUE TITLE
Required runner params

### ISSUE THREAD

**Issue by KTFeigelis** [neuroailab/ptutils#10]
- [x] DB interface same as TFUTils

- [x] Load params w/ default do_restore false, and raise error if same exp_id exists

- [ ] save_params should have all filters same as TFUtils, and enforce metrics_freq for Database bandwidth safety. Also should take in arguments corresponding to model attribute names/dotpaths and their own save frequencies. Or just one frequency for many auxillary intermediate computations. (Alternative is that the user can define this functionality in train loop)

- [x] model_params should be nested dictionaries mapping things that are Base classes to their initialization parameters. model_params should take in a default cuda_device key, which will recursively apply that device to all children in _bases under the get_model call UNLESS those have their own cuda_device key inside their nested dict. If that is the case, this should overwrite the default in model_params. 

- [x] above holds for dataprovider_params

**Comment by bluebelmont** [comment]
deciding to not enforce min freq
