### ISSUE TITLE
questions for alex

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#13]
- what is the distinction between args and kwargs in base? is args necessary?
    - viewing args gives a KeyError 
```
:File "/home/bsheffer/ptutils/ptutils/base.py", line 67, in name
    return self._params['name']
KeyError: 'name'
```
- what is the purpose of base.cast()? doesn't seem to be called anywhere
- what is the CAVEAT in base.to_state?
`159: TODO: CAVEAT GOES HERE`

**Comment by alexandonian** [comment]
1. There isn't a huge distinction. It just gives you two different ways to initialize nested bases (by list or by dictionary). I just wrote about this in the docs, which I'll try to help you guys with. I'm not sure exactly what you did to get that error, but I did just fix something related to that.

2. Cast is a partially implemented method for casting all torch tensors of a given base to a certain dtype, cuda etc. It may come in handy later, but it is not necessary for right now.

3. If I remember correctly, the caveat is that the parameters of a torch.nn.Module will only be included in the global state_dict returned by `base.to_state()` if it has a `ptutils.base.Base` parent (i.e. you can't have `ptutils.base.Base --> randomClass --> torch.nn.Module`, where `isinstance(randomClass, (ptutils.Base, torch.nn.Module))` is `False` and `-->` indicates a parent to child relationship).

**Comment by bluebelmont** [comment]
closing because i'm pretty sure none of these concerns are relevant anymore
