### ISSUE TITLE
implement optional data parallelization

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#14]
pytorch provides easy data parallelization, but it's not clear what we want our defaults to be for ptutils. for now, we're only including capability for models on a single gpu, but in the future will provide a standardized interface for data parallelization

**Comment by anayebi** [comment]
Unlike TensorFlow, data parallelization is simple enough in PyTorch that it should probably just not be standardized for maximum flexibility. This way, users just specify in the model func which layers they want to parallelize (or even the whole model), by passing the DataParallel wrapper at the appropriate point.

**Comment by alexandonian** [comment]
@bluebelmont Can we close this?

**Comment by bluebelmont** [comment]
@anayebi @alexandonian I agree we should allow for maximum flexibility, but until we show that objects with DataParallel wrapper are saved/restored correctly, we should keep this open.

**Comment by bluebelmont** [comment]
something that @yamins81 brought up during our conversation about the sysml abstract was the deficit between PTUtils and TFUtils in terms of dataproviders. He mentioned that the functionality for manipulating and selectively loading parts of large datasets within tfutils is almost enough to constitute a separate set of tools. I think it would be useful to have a discussion at some point about what we want the future of data utilities within (or outside of) PTUtils to look like.

I'm going to close this because, while it would be good to know whether the DataParallel interface works seamlessly with PTUtils as is, this is part of a larger question about how we're going to specify dataproviders in general.
