### ISSUE TITLE
remove periods from state keys

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#17]
mongo doesn't like periods in the document keys, so we need to come up with a naming scheme for serializing the pytorch state dict. An example of the error:

`
File "../ptutils/database.py", line 159, in save
    new_id = self.collection.save(doc_copy)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2445, in save
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 562, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 543, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 424, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 552, in _raise_connection_failure
    raise error
InvalidDocument: key 'linear.weight' must not contain '.'
`

**Comment by alexandonian** [comment]
Blue, Kevin and I determined that the solution to this is to integrate the following functionality into the most recent version of `_mongoify` and `_demongoify`:

```
   def _replace(self, document, replace='.', replacement='__'):
        """Replace `replace` in dictionary keys with `replacement`."""
        for (key, value) in document.items():
            new_key = key.replace(replace, replacement)
            if isinstance(value, dict):
                document[new_key] = self._replace(document.pop(key),
                                                  replace=replace,
                                                  replacement=replacement)
            else:
                document[new_key] = document.pop(key)
        return document

    def _mongoify(self, document):
        return self._replace(document)

    def _de_mongoify(self, document):
        return self._replace(document, replace='__', replacement='.')
```

**Comment by bluebelmont** [comment]
commit 087a2e3402cc364b178c4b5521e4413fbc02916b fixes this
