### ISSUE TITLE
decouple training/testing from loading

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#20]
As far as I can tell, there's no reason to have the only way to restore a model be through `train_from_params` and `test_from_params`. We should think about how to change the interface so that the user can do:

`my_exp = runner.Runner(params)`
`my_exp.train()`

or

`my_exp = runner.Runner(params)`
`my_exp.test()`

**Comment by alexandonian** [comment]
I've come up with an intermediate solution which looks like the following:
```
my_exp = runner.Runner.init(params)
my_exp.train()
```
or
```
my_exp = runner.Runner.init(params)
my_exp.test()
```
