### ISSUE TITLE
SysML Abstract Notes

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#27]
- computational experiments: At scale, essential to be able to save, load, checkpoint in a principled way
- Reproducible aspect: consistency of storing results by pairing with experiment + not conflicting with other experiments, knowing exactly what the training schedule, having all of the information about training stored in a standard ways, ease of repeating experiments
- Neural network training: doing branched training; handle standard, noninteractive case or complex, interactive cases; remapping parts of models
- Interacting with results: saving the results in a modular fashion

**Comment by yamins81** [comment]
Notes from dan on existing abstract:

more evocative title and section headers

maybe you want to have bulleted list of classes and components each with a one-sentence description, pointing to the figure

good things: 
about the dbinterface:
	- defines the global address of an experiment with all the things needed to completely reproduce the experiment

	- makes it easy to generate very customized but simple visualizations even if you're not on the system that the experiment was run on

	- makes it easy to look through your experimental history and find what you did

	- makes it easy to restart training from any location where you can train

	- makes it easy to generate a new model that is partially based on trained components (remapping) from a previous experiment and maintains the links.   so you can visualize experimental history
	

about the runner class: 
	- supports library of standard experiment patterns that is extensible
	- supports standard pattern (train/validate) especially good features for complex validations at scale
	- also nonstandard interactive pattern (where dataprovider is a function of model output)


OUTLINE:
	intro:  describe the main motivations
	PTUtils: the core content
		main classes and what they do
		the experiment addressing concept
		serialization
		the good things
			subset for deepnet stuff
	comparison
		comparison to two types of things:
			i. experiment management software:  here the key point is that the generic tools are too generic and don't meet a lot of domain-specific needs, that's were PTUtils comes in
			ii. deep learning frameworks: 
				    two types of things:  
				    	a. base graph-definition software and implenentions (tensorflow, pytorch)
				    	b. high-level simplification packages for graph def (keras, tf-slim)
				    PUTils is neither of these things.   "PTUtils is not like Keras for PyTorch" and explain why.  it is meant t be compatible with anything that is generic for pytorch. but itself is about experiment management. 
				    We have a similar project in tdevelpoment for tensorflow (reference tfutils repo)
				    

		
	conclusion

**Comment by yamins81** [comment]
abstract is here btw:  https://www.overleaf.com/12773404jknstqmmqymd#/48749168/

**Comment by bluebelmont** [comment]
great success
