### ISSUE TITLE
Fix Base super() call such that it can be called at the bottom of __init__(.)

### ISSUE THREAD

**Issue by KTFeigelis** [neuroailab/ptutils#29]
Currently, all Base classes must call the super.__init__ method at the top of their own __init__ method. If it is called at the end of the method, an infinite recursion is entered. 

This must be fixed due to hard-coded variables inside __init__ which should be overwritten by from_params() but are not due to the ordering.

Example
```

class A(ptutils.base.Base):
    def __init__(self, *args, **kwargs):
        super(A, self).__init__(*args, **kwargs)
        self.x = 0
    def increment_x(self):
         self.x += 1
```

Create an instance of A, then call increment_x multiple times.

Next call a_instance = a_instance.from_params(**a_instance.to_params())

a_instance.x will be 0, instead of the counter value.

**Comment by bluebelmont** [comment]
fixed by aba18fef0ac798dea16eb4120d198ddf5fef3f44
