### ISSUE TITLE
add functionality for loading partial models + namespacing

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#7]
Implement a load_params_dict equivalent to that in tfutils.

## Saving models
In order to allow multiple disjoint tf.nn.modules while ensuring no ambiguity in state_dict keys, we will aggregate all state_dicts in a single state_dict to save with the same naming convention as pt's default.

## Loading models

pt's default load_state_dict is not fully sufficient for reconstructing our models, so we must write our own functionality for loading which allows:

1. Loading model from trained model with identical structure  
2. Partially loading model from trained model with identical structure (i.e. reinitialize some tensors)
3. Loading parts of a trained model into a new model with different structure

If a mapping is specified, any tensors in the model being loaded which do _not_ have a specified mapping will be initialized from scratch. Regex on the names of the variables that you want to keep

**Comment by alexandonian** [comment]
See `TestBase` test methods starting [test_to_state](https://github.com/neuroailab/ptutils/blob/master/ptutils/tests/test.py#L76).

1. The default behavior of `from_state` loads an arbitrary base object from the saved state of an identical base object. The base object may or may not be and/or contain a trained model.
2. The keyword argument to `restore_params` specifies which parameters should be restored from the saved state. All other parameters will be reinitialized. If `restore_params` is None, then all parameters will be restored.
3. The keyword argument `param_mapping` allows you to rename old parameters with the names of parameters present in a new model. Currently, this mapping has no bearing on whether the parameters are initialized from scratch of restored. That is specified completely by `restore_params`.
